# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'joystickdialogtemplate.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JoystickDialog(object):
    def setupUi(self, JoystickDialog):
        JoystickDialog.setObjectName("JoystickDialog")
        JoystickDialog.resize(563, 212)
        self.verticalLayout = QtWidgets.QVBoxLayout(JoystickDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.value_lbl = QtWidgets.QLabel(JoystickDialog)
        self.value_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.value_lbl.setObjectName("value_lbl")
        self.gridLayout.addWidget(self.value_lbl, 0, 1, 1, 1)
        self.inverted_btn = QtWidgets.QCheckBox(JoystickDialog)
        self.inverted_btn.setToolTip("")
        self.inverted_btn.setObjectName("inverted_btn")
        self.gridLayout.addWidget(self.inverted_btn, 1, 3, 1, 1)
        self.mapping_lbl = QtWidgets.QLabel(JoystickDialog)
        self.mapping_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.mapping_lbl.setObjectName("mapping_lbl")
        self.gridLayout.addWidget(self.mapping_lbl, 0, 2, 1, 1)
        self.invert_lbl = QtWidgets.QLabel(JoystickDialog)
        self.invert_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.invert_lbl.setObjectName("invert_lbl")
        self.gridLayout.addWidget(self.invert_lbl, 0, 3, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(JoystickDialog)
        self.progressBar.setToolTip("")
        self.progressBar.setMinimum(-32767)
        self.progressBar.setMaximum(32766)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 1, 1, 1)
        self.mapping_combo = QtWidgets.QComboBox(JoystickDialog)
        self.mapping_combo.setMinimumSize(QtCore.QSize(130, 0))
        self.mapping_combo.setToolTip("")
        self.mapping_combo.setObjectName("mapping_combo")
        self.mapping_combo.addItem("")
        self.mapping_combo.addItem("")
        self.mapping_combo.addItem("")
        self.mapping_combo.addItem("")
        self.mapping_combo.addItem("")
        self.mapping_combo.addItem("")
        self.gridLayout.addWidget(self.mapping_combo, 1, 2, 1, 1)
        self.axin_n_lbl = QtWidgets.QLabel(JoystickDialog)
        self.axin_n_lbl.setToolTip("")
        self.axin_n_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.axin_n_lbl.setObjectName("axin_n_lbl")
        self.gridLayout.addWidget(self.axin_n_lbl, 1, 0, 1, 1)
        self.axis_lbl = QtWidgets.QLabel(JoystickDialog)
        self.axis_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.axis_lbl.setObjectName("axis_lbl")
        self.gridLayout.addWidget(self.axis_lbl, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.deadBandLabel = QtWidgets.QLabel(JoystickDialog)
        self.deadBandLabel.setObjectName("deadBandLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.deadBandLabel)
        self.deadband_spinbox = QtWidgets.QSpinBox(JoystickDialog)
        self.deadband_spinbox.setToolTip("")
        self.deadband_spinbox.setMaximum(32766)
        self.deadband_spinbox.setSingleStep(100)
        self.deadband_spinbox.setProperty("value", 2000)
        self.deadband_spinbox.setObjectName("deadband_spinbox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deadband_spinbox)
        self.expoLabel = QtWidgets.QLabel(JoystickDialog)
        self.expoLabel.setObjectName("expoLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.expoLabel)
        self.expo_spinbox = QtWidgets.QDoubleSpinBox(JoystickDialog)
        self.expo_spinbox.setToolTip("")
        self.expo_spinbox.setDecimals(1)
        self.expo_spinbox.setMaximum(1.0)
        self.expo_spinbox.setSingleStep(0.1)
        self.expo_spinbox.setObjectName("expo_spinbox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.expo_spinbox)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(JoystickDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(JoystickDialog)
        self.buttonBox.accepted.connect(JoystickDialog.accept)
        self.buttonBox.rejected.connect(JoystickDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(JoystickDialog)

    def retranslateUi(self, JoystickDialog):
        _translate = QtCore.QCoreApplication.translate
        JoystickDialog.setWindowTitle(_translate("JoystickDialog", "Joystick configuration"))
        self.value_lbl.setText(_translate("JoystickDialog", "Value"))
        self.mapping_lbl.setText(_translate("JoystickDialog", "Mapping"))
        self.invert_lbl.setText(_translate("JoystickDialog", "Invert"))
        self.progressBar.setFormat(_translate("JoystickDialog", "%v"))
        self.mapping_combo.setItemText(0, _translate("JoystickDialog", "None"))
        self.mapping_combo.setItemText(1, _translate("JoystickDialog", "North / south"))
        self.mapping_combo.setItemText(2, _translate("JoystickDialog", "East / west"))
        self.mapping_combo.setItemText(3, _translate("JoystickDialog", "Front / back"))
        self.mapping_combo.setItemText(4, _translate("JoystickDialog", "Left / right"))
        self.mapping_combo.setItemText(5, _translate("JoystickDialog", "Timeshift"))
        self.axin_n_lbl.setText(_translate("JoystickDialog", "1"))
        self.axis_lbl.setText(_translate("JoystickDialog", "Axis"))
        self.deadBandLabel.setText(_translate("JoystickDialog", "Dead-band:"))
        self.expoLabel.setText(_translate("JoystickDialog", "Expo:"))


