# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 730)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.hostLabel = QtWidgets.QLabel(self.groupBox)
        self.hostLabel.setObjectName("hostLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.hostLabel)
        self.hostEdit = QtWidgets.QLineEdit(self.groupBox)
        self.hostEdit.setObjectName("hostEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hostEdit)
        self.portLabel = QtWidgets.QLabel(self.groupBox)
        self.portLabel.setObjectName("portLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.telescopeLabel_2 = QtWidgets.QLabel(self.groupBox)
        self.telescopeLabel_2.setEnabled(False)
        self.telescopeLabel_2.setObjectName("telescopeLabel_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.telescopeLabel_2)
        self.telescopeComboBox = QtWidgets.QComboBox(self.groupBox)
        self.telescopeComboBox.setEnabled(False)
        self.telescopeComboBox.setObjectName("telescopeComboBox")
        self.telescopeComboBox.addItem("")
        self.telescopeComboBox.setItemText(0, "")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.telescopeComboBox)
        self.joystickLabel_2 = QtWidgets.QLabel(self.groupBox)
        self.joystickLabel_2.setEnabled(False)
        self.joystickLabel_2.setObjectName("joystickLabel_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.joystickLabel_2)
        self.joystickCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.joystickCheckBox.setEnabled(False)
        self.joystickCheckBox.setObjectName("joystickCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.joystickCheckBox)
        self.portEdit = QtWidgets.QSpinBox(self.groupBox)
        self.portEdit.setMaximum(65535)
        self.portEdit.setProperty("value", 7624)
        self.portEdit.setObjectName("portEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.portEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.connectButton = QtWidgets.QPushButton(self.groupBox)
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout.addWidget(self.connectButton)
        self.indiLabel = QtWidgets.QLabel(self.groupBox)
        self.indiLabel.setText("")
        self.indiLabel.setObjectName("indiLabel")
        self.verticalLayout.addWidget(self.indiLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.methodLabel = QtWidgets.QLabel(self.groupBox_4)
        self.methodLabel.setObjectName("methodLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.methodLabel)
        self.trackingComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.trackingComboBox.setObjectName("trackingComboBox")
        self.trackingComboBox.addItem("")
        self.trackingComboBox.addItem("")
        self.trackingComboBox.addItem("")
        self.trackingComboBox.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.trackingComboBox)
        self.pGainLabel = QtWidgets.QLabel(self.groupBox_4)
        self.pGainLabel.setObjectName("pGainLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pGainLabel)
        self.pGainSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.pGainSpinBox.setObjectName("pGainSpinBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pGainSpinBox)
        self.tauILabel = QtWidgets.QLabel(self.groupBox_4)
        self.tauILabel.setObjectName("tauILabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tauILabel)
        self.tauISpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.tauISpinBox.setObjectName("tauISpinBox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tauISpinBox)
        self.tauDLabel = QtWidgets.QLabel(self.groupBox_4)
        self.tauDLabel.setObjectName("tauDLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.tauDLabel)
        self.tauDSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.tauDSpinBox.setObjectName("tauDSpinBox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tauDSpinBox)
        self.maxRateLabel = QtWidgets.QLabel(self.groupBox_4)
        self.maxRateLabel.setObjectName("maxRateLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.maxRateLabel)
        self.saturationLabel = QtWidgets.QLabel(self.groupBox_4)
        self.saturationLabel.setObjectName("saturationLabel")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.saturationLabel)
        self.saturationSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.saturationSpinBox.setObjectName("saturationSpinBox")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.saturationSpinBox)
        self.maxRateSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.maxRateSpinBox.setObjectName("maxRateSpinBox")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.maxRateSpinBox)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.trackButton = QtWidgets.QPushButton(self.groupBox_4)
        self.trackButton.setObjectName("trackButton")
        self.verticalLayout_5.addWidget(self.trackButton)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.latitudeLabel = QtWidgets.QLabel(self.groupBox_3)
        self.latitudeLabel.setObjectName("latitudeLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.latitudeLabel)
        self.latitudeEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.latitudeEdit.setObjectName("latitudeEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.latitudeEdit)
        self.longitudeLabel = QtWidgets.QLabel(self.groupBox_3)
        self.longitudeLabel.setObjectName("longitudeLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.longitudeLabel)
        self.longitudeEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.longitudeEdit.setObjectName("longitudeEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.longitudeEdit)
        self.altitudeLabel = QtWidgets.QLabel(self.groupBox_3)
        self.altitudeLabel.setObjectName("altitudeLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.altitudeLabel)
        self.altitudeSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.altitudeSpinBox.setMaximum(999999)
        self.altitudeSpinBox.setObjectName("altitudeSpinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.altitudeSpinBox)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.locationLabel = QtWidgets.QLabel(self.groupBox_3)
        self.locationLabel.setObjectName("locationLabel")
        self.verticalLayout_3.addWidget(self.locationLabel)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.realTimeButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.realTimeButton.setChecked(True)
        self.realTimeButton.setObjectName("realTimeButton")
        self.verticalLayout_2.addWidget(self.realTimeButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.simuTimeButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.simuTimeButton.setObjectName("simuTimeButton")
        self.horizontalLayout_2.addWidget(self.simuTimeButton)
        self.setTimeButton = QtWidgets.QPushButton(self.groupBox_5)
        self.setTimeButton.setEnabled(False)
        self.setTimeButton.setObjectName("setTimeButton")
        self.horizontalLayout_2.addWidget(self.setTimeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.catalogSatButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.catalogSatButton.setChecked(True)
        self.catalogSatButton.setObjectName("catalogSatButton")
        self.horizontalLayout.addWidget(self.catalogSatButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.catalogConfigButton = QtWidgets.QPushButton(self.groupBox_2)
        self.catalogConfigButton.setObjectName("catalogConfigButton")
        self.horizontalLayout.addWidget(self.catalogConfigButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.satComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.satComboBox.setEnabled(True)
        self.satComboBox.setEditable(True)
        self.satComboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.satComboBox.setObjectName("satComboBox")
        self.satComboBox.addItem("")
        self.satComboBox.addItem("")
        self.satComboBox.addItem("")
        self.satComboBox.addItem("")
        self.satComboBox.addItem("")
        self.verticalLayout_4.addWidget(self.satComboBox)
        self.tleSatButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.tleSatButton.setObjectName("tleSatButton")
        self.verticalLayout_4.addWidget(self.tleSatButton)
        self.tleEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.tleEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tleEdit.sizePolicy().hasHeightForWidth())
        self.tleEdit.setSizePolicy(sizePolicy)
        self.tleEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.tleEdit.setReadOnly(False)
        self.tleEdit.setCenterOnScroll(False)
        self.tleEdit.setObjectName("tleEdit")
        self.verticalLayout_4.addWidget(self.tleEdit)
        self.satLabel = QtWidgets.QLabel(self.groupBox_2)
        self.satLabel.setObjectName("satLabel")
        self.verticalLayout_4.addWidget(self.satLabel)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_6)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_8.addWidget(self.graphicsView)
        self.verticalLayout_10.addWidget(self.groupBox_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.timeLabel = QtWidgets.QLabel(self.groupBox_7)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout_3.addWidget(self.timeLabel)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(20, -1, -1, -1)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.satAzLabel = QtWidgets.QLabel(self.groupBox_7)
        self.satAzLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.satAzLabel.setObjectName("satAzLabel")
        self.gridLayout.addWidget(self.satAzLabel, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.satAltLabel = QtWidgets.QLabel(self.groupBox_7)
        self.satAltLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.satAltLabel.setObjectName("satAltLabel")
        self.gridLayout.addWidget(self.satAltLabel, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.satDistLabel = QtWidgets.QLabel(self.groupBox_7)
        self.satDistLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.satDistLabel.setObjectName("satDistLabel")
        self.gridLayout.addWidget(self.satDistLabel, 4, 1, 1, 1)
        self.satDecLabel = QtWidgets.QLabel(self.groupBox_7)
        self.satDecLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.satDecLabel.setObjectName("satDecLabel")
        self.gridLayout.addWidget(self.satDecLabel, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 5, 0, 1, 1)
        self.satShadowLabel = QtWidgets.QLabel(self.groupBox_7)
        self.satShadowLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.satShadowLabel.setObjectName("satShadowLabel")
        self.gridLayout.addWidget(self.satShadowLabel, 5, 1, 1, 1)
        self.satRaLabel = QtWidgets.QLabel(self.groupBox_7)
        self.satRaLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.satRaLabel.setObjectName("satRaLabel")
        self.gridLayout.addWidget(self.satRaLabel, 0, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(20, -1, -1, -1)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_23 = QtWidgets.QLabel(self.groupBox_7)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_7)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 3, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_7)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 2, 0, 1, 1)
        self.telRaLabel = QtWidgets.QLabel(self.groupBox_7)
        self.telRaLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.telRaLabel.setObjectName("telRaLabel")
        self.gridLayout_2.addWidget(self.telRaLabel, 0, 1, 1, 1)
        self.telDecLabel = QtWidgets.QLabel(self.groupBox_7)
        self.telDecLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.telDecLabel.setObjectName("telDecLabel")
        self.gridLayout_2.addWidget(self.telDecLabel, 1, 1, 1, 1)
        self.telAltLabel = QtWidgets.QLabel(self.groupBox_7)
        self.telAltLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.telAltLabel.setObjectName("telAltLabel")
        self.gridLayout_2.addWidget(self.telAltLabel, 2, 1, 1, 1)
        self.telAzLabel = QtWidgets.QLabel(self.groupBox_7)
        self.telAzLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.telAzLabel.setObjectName("telAzLabel")
        self.gridLayout_2.addWidget(self.telAzLabel, 3, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_2)
        self.label_26 = QtWidgets.QLabel(self.groupBox_7)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_9.addWidget(self.label_26)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(20, -1, -1, -1)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_27 = QtWidgets.QLabel(self.groupBox_7)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_7)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 1, 0, 1, 1)
        self.diffRaLabel = QtWidgets.QLabel(self.groupBox_7)
        self.diffRaLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.diffRaLabel.setObjectName("diffRaLabel")
        self.gridLayout_3.addWidget(self.diffRaLabel, 0, 1, 1, 1)
        self.diffDecLabel = QtWidgets.QLabel(self.groupBox_7)
        self.diffDecLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.diffDecLabel.setObjectName("diffDecLabel")
        self.gridLayout_3.addWidget(self.diffDecLabel, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.verticalLayout_10.addWidget(self.groupBox_7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.logBrowser = QtWidgets.QTextBrowser(self.groupBox_8)
        self.logBrowser.setObjectName("logBrowser")
        self.verticalLayout_11.addWidget(self.logBrowser)
        self.verticalLayout_12.addWidget(self.groupBox_8)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pysattrack"))
        self.groupBox.setTitle(_translate("MainWindow", "INDI"))
        self.hostLabel.setText(_translate("MainWindow", "Host:"))
        self.hostEdit.setText(_translate("MainWindow", "localhost"))
        self.portLabel.setText(_translate("MainWindow", "Port:"))
        self.telescopeLabel_2.setText(_translate("MainWindow", "Telescope"))
        self.joystickLabel_2.setText(_translate("MainWindow", "Joystick:"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Tracking"))
        self.methodLabel.setText(_translate("MainWindow", "Method:"))
        self.trackingComboBox.setItemText(0, _translate("MainWindow", "Goto"))
        self.trackingComboBox.setItemText(1, _translate("MainWindow", "Move"))
        self.trackingComboBox.setItemText(2, _translate("MainWindow", "Timed moves"))
        self.trackingComboBox.setItemText(3, _translate("MainWindow", "Speed"))
        self.pGainLabel.setText(_translate("MainWindow", "P gain:"))
        self.tauILabel.setText(_translate("MainWindow", "Tau I"))
        self.tauDLabel.setText(_translate("MainWindow", "Tau D"))
        self.maxRateLabel.setText(_translate("MainWindow", "Max rate:"))
        self.saturationLabel.setText(_translate("MainWindow", "Saturation:"))
        self.trackButton.setText(_translate("MainWindow", "Track"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Location"))
        self.latitudeLabel.setText(_translate("MainWindow", "Latitude:"))
        self.longitudeLabel.setText(_translate("MainWindow", "Longitude:"))
        self.altitudeLabel.setText(_translate("MainWindow", "Altitude"))
        self.altitudeSpinBox.setSuffix(_translate("MainWindow", " m"))
        self.locationLabel.setText(_translate("MainWindow", "Valid location"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Time"))
        self.realTimeButton.setText(_translate("MainWindow", "from computer cloc&k"))
        self.simuTimeButton.setText(_translate("MainWindow", "Simu&lation"))
        self.setTimeButton.setText(_translate("MainWindow", "Set time"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Satellite"))
        self.catalogSatButton.setText(_translate("MainWindow", "Fro&m catalog"))
        self.catalogConfigButton.setText(_translate("MainWindow", "Config"))
        self.satComboBox.setItemText(0, _translate("MainWindow", "ISS"))
        self.satComboBox.setItemText(1, _translate("MainWindow", "Hubble"))
        self.satComboBox.setItemText(2, _translate("MainWindow", "IRIDIUM 10"))
        self.satComboBox.setItemText(3, _translate("MainWindow", "IRIDIUM 11"))
        self.satComboBox.setItemText(4, _translate("MainWindow", "O3B"))
        self.tleSatButton.setText(_translate("MainWindow", "From &TLE"))
        self.satLabel.setText(_translate("MainWindow", "Valid elements, 3.1day old"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Starchart"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Status"))
        self.label_5.setText(_translate("MainWindow", "Time:"))
        self.timeLabel.setText(_translate("MainWindow", "2019-02-22 23:00:00"))
        self.label_7.setText(_translate("MainWindow", "Satellite position:"))
        self.satAzLabel.setText(_translate("MainWindow", "12°12\'13\""))
        self.label_10.setText(_translate("MainWindow", "Alt:"))
        self.satAltLabel.setText(_translate("MainWindow", "12°12\'13\""))
        self.label_11.setText(_translate("MainWindow", "Az:"))
        self.satDistLabel.setText(_translate("MainWindow", "9999 km"))
        self.satDecLabel.setText(_translate("MainWindow", "12°12\'13\""))
        self.label_16.setText(_translate("MainWindow", "Distance:"))
        self.label_9.setText(_translate("MainWindow", "DEC:"))
        self.label_8.setText(_translate("MainWindow", "RA:"))
        self.label_19.setText(_translate("MainWindow", "In shadow:"))
        self.satShadowLabel.setText(_translate("MainWindow", "No"))
        self.satRaLabel.setText(_translate("MainWindow", "12h12\'13\""))
        self.label_12.setText(_translate("MainWindow", "Telescope position:"))
        self.label_23.setText(_translate("MainWindow", "DEC:"))
        self.label_21.setText(_translate("MainWindow", "RA:"))
        self.label_25.setText(_translate("MainWindow", "Az:"))
        self.label_24.setText(_translate("MainWindow", "Alt:"))
        self.telRaLabel.setText(_translate("MainWindow", "12h12\'13\""))
        self.telDecLabel.setText(_translate("MainWindow", "12°12\'13\""))
        self.telAltLabel.setText(_translate("MainWindow", "12°12\'13\""))
        self.telAzLabel.setText(_translate("MainWindow", "12°12\'13\""))
        self.label_26.setText(_translate("MainWindow", "Difference:"))
        self.label_27.setText(_translate("MainWindow", "RA:"))
        self.label_29.setText(_translate("MainWindow", "DEC:"))
        self.diffRaLabel.setText(_translate("MainWindow", "12h12\'13\""))
        self.diffDecLabel.setText(_translate("MainWindow", "12°12\'13\""))
        self.groupBox_8.setTitle(_translate("MainWindow", "Log"))

