# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1235, 819)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pysattrack/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.setSpacing(6)
        self.main_layout.setObjectName("main_layout")
        self.indi_time_location_layout = QtWidgets.QVBoxLayout()
        self.indi_time_location_layout.setSpacing(6)
        self.indi_time_location_layout.setObjectName("indi_time_location_layout")
        self.indi_box = QtWidgets.QGroupBox(self.central_widget)
        self.indi_box.setObjectName("indi_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.indi_box)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.host_lbl = QtWidgets.QLabel(self.indi_box)
        self.host_lbl.setObjectName("host_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.host_lbl)
        self.host_edit = QtWidgets.QLineEdit(self.indi_box)
        self.host_edit.setObjectName("host_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.host_edit)
        self.port_lbl = QtWidgets.QLabel(self.indi_box)
        self.port_lbl.setObjectName("port_lbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.port_lbl)
        self.port_edit = QtWidgets.QSpinBox(self.indi_box)
        self.port_edit.setMaximum(65535)
        self.port_edit.setProperty("value", 7624)
        self.port_edit.setObjectName("port_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.port_edit)
        self.telescope_lbl = QtWidgets.QLabel(self.indi_box)
        self.telescope_lbl.setEnabled(False)
        self.telescope_lbl.setObjectName("telescope_lbl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.telescope_lbl)
        self.telescope_combobox = QtWidgets.QComboBox(self.indi_box)
        self.telescope_combobox.setEnabled(False)
        self.telescope_combobox.setObjectName("telescope_combobox")
        self.telescope_combobox.addItem("")
        self.telescope_combobox.setItemText(0, "")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.telescope_combobox)
        self.verticalLayout.addLayout(self.formLayout)
        self.connect_btn = QtWidgets.QPushButton(self.indi_box)
        self.connect_btn.setObjectName("connect_btn")
        self.verticalLayout.addWidget(self.connect_btn)
        self.indi_lbl = QtWidgets.QLabel(self.indi_box)
        self.indi_lbl.setObjectName("indi_lbl")
        self.verticalLayout.addWidget(self.indi_lbl)
        self.indi_time_location_layout.addWidget(self.indi_box)
        self.time_box = QtWidgets.QGroupBox(self.central_widget)
        self.time_box.setObjectName("time_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.time_box)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.real_time_btn = QtWidgets.QRadioButton(self.time_box)
        self.real_time_btn.setChecked(True)
        self.real_time_btn.setObjectName("real_time_btn")
        self.verticalLayout_2.addWidget(self.real_time_btn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.simu_time_btn = QtWidgets.QRadioButton(self.time_box)
        self.simu_time_btn.setObjectName("simu_time_btn")
        self.horizontalLayout_2.addWidget(self.simu_time_btn)
        self.set_time_btn = QtWidgets.QPushButton(self.time_box)
        self.set_time_btn.setEnabled(False)
        self.set_time_btn.setObjectName("set_time_btn")
        self.horizontalLayout_2.addWidget(self.set_time_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.indi_time_location_layout.addWidget(self.time_box)
        self.location_box = QtWidgets.QGroupBox(self.central_widget)
        self.location_box.setObjectName("location_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.location_box)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.latitude_lbl = QtWidgets.QLabel(self.location_box)
        self.latitude_lbl.setObjectName("latitude_lbl")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.latitude_lbl)
        self.latitude_edit = QtWidgets.QLineEdit(self.location_box)
        self.latitude_edit.setObjectName("latitude_edit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.latitude_edit)
        self.longitude_lbl = QtWidgets.QLabel(self.location_box)
        self.longitude_lbl.setObjectName("longitude_lbl")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.longitude_lbl)
        self.longitude_edit = QtWidgets.QLineEdit(self.location_box)
        self.longitude_edit.setObjectName("longitude_edit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.longitude_edit)
        self.altitude_lbl = QtWidgets.QLabel(self.location_box)
        self.altitude_lbl.setObjectName("altitude_lbl")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.altitude_lbl)
        self.altitude_spinbox = QtWidgets.QSpinBox(self.location_box)
        self.altitude_spinbox.setMaximum(999999)
        self.altitude_spinbox.setObjectName("altitude_spinbox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.altitude_spinbox)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.location_lbl = QtWidgets.QLabel(self.location_box)
        self.location_lbl.setObjectName("location_lbl")
        self.verticalLayout_3.addWidget(self.location_lbl)
        self.indi_time_location_layout.addWidget(self.location_box)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.indi_time_location_layout.addItem(spacerItem)
        self.main_layout.addLayout(self.indi_time_location_layout)
        self.tracking_control_layout = QtWidgets.QVBoxLayout()
        self.tracking_control_layout.setSpacing(6)
        self.tracking_control_layout.setObjectName("tracking_control_layout")
        self.tracking_box = QtWidgets.QGroupBox(self.central_widget)
        self.tracking_box.setAutoFillBackground(False)
        self.tracking_box.setObjectName("tracking_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tracking_box)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tracking_layout = QtWidgets.QFormLayout()
        self.tracking_layout.setSpacing(6)
        self.tracking_layout.setObjectName("tracking_layout")
        self.p_gain_lbl = QtWidgets.QLabel(self.tracking_box)
        self.p_gain_lbl.setObjectName("p_gain_lbl")
        self.tracking_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.p_gain_lbl)
        self.p_gain_spinbox = QtWidgets.QDoubleSpinBox(self.tracking_box)
        self.p_gain_spinbox.setObjectName("p_gain_spinbox")
        self.tracking_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.p_gain_spinbox)
        self.max_speed_DE_lbl = QtWidgets.QLabel(self.tracking_box)
        self.max_speed_DE_lbl.setObjectName("max_speed_DE_lbl")
        self.tracking_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.max_speed_DE_lbl)
        self.max_speed_DE_spinbox = QtWidgets.QDoubleSpinBox(self.tracking_box)
        self.max_speed_DE_spinbox.setMinimum(-99.99)
        self.max_speed_DE_spinbox.setMaximum(99.99)
        self.max_speed_DE_spinbox.setSingleStep(0.1)
        self.max_speed_DE_spinbox.setObjectName("max_speed_DE_spinbox")
        self.tracking_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.max_speed_DE_spinbox)
        self.joystick_speed_lbl = QtWidgets.QLabel(self.tracking_box)
        self.joystick_speed_lbl.setObjectName("joystick_speed_lbl")
        self.tracking_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.joystick_speed_lbl)
        self.joystick_speed_spinbox = QtWidgets.QDoubleSpinBox(self.tracking_box)
        self.joystick_speed_spinbox.setObjectName("joystick_speed_spinbox")
        self.tracking_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.joystick_speed_spinbox)
        self.joystick_lbl = QtWidgets.QLabel(self.tracking_box)
        self.joystick_lbl.setEnabled(False)
        self.joystick_lbl.setObjectName("joystick_lbl")
        self.tracking_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.joystick_lbl)
        self.joystick_btn = QtWidgets.QPushButton(self.tracking_box)
        self.joystick_btn.setEnabled(False)
        self.joystick_btn.setObjectName("joystick_btn")
        self.tracking_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.joystick_btn)
        self.max_speed_RA_lbl = QtWidgets.QLabel(self.tracking_box)
        self.max_speed_RA_lbl.setObjectName("max_speed_RA_lbl")
        self.tracking_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.max_speed_RA_lbl)
        self.max_speed_RA_spinbox = QtWidgets.QDoubleSpinBox(self.tracking_box)
        self.max_speed_RA_spinbox.setMinimum(-99.99)
        self.max_speed_RA_spinbox.setSingleStep(0.1)
        self.max_speed_RA_spinbox.setObjectName("max_speed_RA_spinbox")
        self.tracking_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.max_speed_RA_spinbox)
        self.verticalLayout_5.addLayout(self.tracking_layout)
        self.tracking_control_layout.addWidget(self.tracking_box)
        self.control_box = QtWidgets.QGroupBox(self.central_widget)
        self.control_box.setObjectName("control_box")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.control_box)
        self.verticalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.control_grid_layout = QtWidgets.QGridLayout()
        self.control_grid_layout.setSpacing(15)
        self.control_grid_layout.setObjectName("control_grid_layout")
        self.down_btn = QtWidgets.QPushButton(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.down_btn.sizePolicy().hasHeightForWidth())
        self.down_btn.setSizePolicy(sizePolicy)
        self.down_btn.setMinimumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.down_btn.setFont(font)
        self.down_btn.setObjectName("down_btn")
        self.control_grid_layout.addWidget(self.down_btn, 2, 1, 1, 1)
        self.center_btn = QtWidgets.QPushButton(self.control_box)
        self.center_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.center_btn.sizePolicy().hasHeightForWidth())
        self.center_btn.setSizePolicy(sizePolicy)
        self.center_btn.setMinimumSize(QtCore.QSize(75, 50))
        self.center_btn.setObjectName("center_btn")
        self.control_grid_layout.addWidget(self.center_btn, 1, 1, 1, 1)
        self.left_btn = QtWidgets.QPushButton(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_btn.sizePolicy().hasHeightForWidth())
        self.left_btn.setSizePolicy(sizePolicy)
        self.left_btn.setMinimumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.left_btn.setFont(font)
        self.left_btn.setObjectName("left_btn")
        self.control_grid_layout.addWidget(self.left_btn, 1, 0, 1, 1)
        self.down_left_btn = QtWidgets.QPushButton(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.down_left_btn.sizePolicy().hasHeightForWidth())
        self.down_left_btn.setSizePolicy(sizePolicy)
        self.down_left_btn.setMinimumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.down_left_btn.setFont(font)
        self.down_left_btn.setObjectName("down_left_btn")
        self.control_grid_layout.addWidget(self.down_left_btn, 2, 0, 1, 1)
        self.up_right_btn = QtWidgets.QPushButton(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_right_btn.sizePolicy().hasHeightForWidth())
        self.up_right_btn.setSizePolicy(sizePolicy)
        self.up_right_btn.setMinimumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.up_right_btn.setFont(font)
        self.up_right_btn.setObjectName("up_right_btn")
        self.control_grid_layout.addWidget(self.up_right_btn, 0, 2, 1, 1)
        self.right_btn = QtWidgets.QPushButton(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_btn.sizePolicy().hasHeightForWidth())
        self.right_btn.setSizePolicy(sizePolicy)
        self.right_btn.setMinimumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.right_btn.setFont(font)
        self.right_btn.setObjectName("right_btn")
        self.control_grid_layout.addWidget(self.right_btn, 1, 2, 1, 1)
        self.up_btn = QtWidgets.QPushButton(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_btn.sizePolicy().hasHeightForWidth())
        self.up_btn.setSizePolicy(sizePolicy)
        self.up_btn.setMinimumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.up_btn.setFont(font)
        self.up_btn.setObjectName("up_btn")
        self.control_grid_layout.addWidget(self.up_btn, 0, 1, 1, 1)
        self.up_left_btn = QtWidgets.QPushButton(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_left_btn.sizePolicy().hasHeightForWidth())
        self.up_left_btn.setSizePolicy(sizePolicy)
        self.up_left_btn.setMinimumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(20)
        self.up_left_btn.setFont(font)
        self.up_left_btn.setObjectName("up_left_btn")
        self.control_grid_layout.addWidget(self.up_left_btn, 0, 0, 1, 1)
        self.down_right_btn = QtWidgets.QPushButton(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.down_right_btn.sizePolicy().hasHeightForWidth())
        self.down_right_btn.setSizePolicy(sizePolicy)
        self.down_right_btn.setMinimumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.down_right_btn.setFont(font)
        self.down_right_btn.setObjectName("down_right_btn")
        self.control_grid_layout.addWidget(self.down_right_btn, 2, 2, 1, 1)
        self.slow_btn = QtWidgets.QPushButton(self.control_box)
        self.slow_btn.setObjectName("slow_btn")
        self.control_grid_layout.addWidget(self.slow_btn, 3, 0, 1, 1)
        self.fast_btn = QtWidgets.QPushButton(self.control_box)
        self.fast_btn.setObjectName("fast_btn")
        self.control_grid_layout.addWidget(self.fast_btn, 3, 2, 1, 1)
        self.speed_lbl = QtWidgets.QLabel(self.control_box)
        self.speed_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_lbl.setObjectName("speed_lbl")
        self.control_grid_layout.addWidget(self.speed_lbl, 3, 1, 1, 1)
        self.verticalLayout_13.addLayout(self.control_grid_layout)
        self.tracking_control_layout.addWidget(self.control_box)
        self.main_layout.addLayout(self.tracking_control_layout)
        self.satellite_layout = QtWidgets.QVBoxLayout()
        self.satellite_layout.setSpacing(6)
        self.satellite_layout.setObjectName("satellite_layout")
        self.satellite_box = QtWidgets.QGroupBox(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.satellite_box.sizePolicy().hasHeightForWidth())
        self.satellite_box.setSizePolicy(sizePolicy)
        self.satellite_box.setObjectName("satellite_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.satellite_box)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.catalog_sat_btn = QtWidgets.QRadioButton(self.satellite_box)
        self.catalog_sat_btn.setChecked(True)
        self.catalog_sat_btn.setObjectName("catalog_sat_btn")
        self.horizontalLayout.addWidget(self.catalog_sat_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.catalog_config_btn = QtWidgets.QPushButton(self.satellite_box)
        self.catalog_config_btn.setObjectName("catalog_config_btn")
        self.horizontalLayout.addWidget(self.catalog_config_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.sat_combobox = QtWidgets.QComboBox(self.satellite_box)
        self.sat_combobox.setEnabled(True)
        self.sat_combobox.setEditable(True)
        self.sat_combobox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.sat_combobox.setObjectName("sat_combobox")
        self.sat_combobox.addItem("")
        self.sat_combobox.addItem("")
        self.sat_combobox.addItem("")
        self.sat_combobox.addItem("")
        self.sat_combobox.addItem("")
        self.verticalLayout_4.addWidget(self.sat_combobox)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tle_sat_btn = QtWidgets.QRadioButton(self.satellite_box)
        self.tle_sat_btn.setObjectName("tle_sat_btn")
        self.horizontalLayout_9.addWidget(self.tle_sat_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.set_TLE_btn = QtWidgets.QPushButton(self.satellite_box)
        self.set_TLE_btn.setEnabled(False)
        self.set_TLE_btn.setObjectName("set_TLE_btn")
        self.horizontalLayout_9.addWidget(self.set_TLE_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.sat_lbl = QtWidgets.QLabel(self.satellite_box)
        self.sat_lbl.setObjectName("sat_lbl")
        self.verticalLayout_4.addWidget(self.sat_lbl)
        self.satellite_layout.addWidget(self.satellite_box)
        self.pass_box = QtWidgets.QGroupBox(self.central_widget)
        self.pass_box.setObjectName("pass_box")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pass_box)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pass_grid = QtWidgets.QGridLayout()
        self.pass_grid.setSpacing(6)
        self.pass_grid.setObjectName("pass_grid")
        self.label_3 = QtWidgets.QLabel(self.pass_box)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pass_grid.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.pass_box)
        self.label_14.setIndent(20)
        self.label_14.setObjectName("label_14")
        self.pass_grid.addWidget(self.label_14, 10, 0, 1, 1)
        self.meridian_time_lbl = QtWidgets.QLabel(self.pass_box)
        self.meridian_time_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meridian_time_lbl.setObjectName("meridian_time_lbl")
        self.pass_grid.addWidget(self.meridian_time_lbl, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.pass_box)
        self.label_13.setIndent(20)
        self.label_13.setObjectName("label_13")
        self.pass_grid.addWidget(self.label_13, 1, 0, 1, 1)
        self.set_az_lbl = QtWidgets.QLabel(self.pass_box)
        self.set_az_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.set_az_lbl.setObjectName("set_az_lbl")
        self.pass_grid.addWidget(self.set_az_lbl, 14, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.pass_box)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pass_grid.addWidget(self.label, 0, 0, 1, 1)
        self.meridian_az_lbl = QtWidgets.QLabel(self.pass_box)
        self.meridian_az_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meridian_az_lbl.setObjectName("meridian_az_lbl")
        self.pass_grid.addWidget(self.meridian_az_lbl, 6, 1, 1, 1)
        self.rise_az_lbl = QtWidgets.QLabel(self.pass_box)
        self.rise_az_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rise_az_lbl.setObjectName("rise_az_lbl")
        self.pass_grid.addWidget(self.rise_az_lbl, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.pass_box)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pass_grid.addWidget(self.label_2, 9, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.pass_box)
        self.label_17.setIndent(20)
        self.label_17.setObjectName("label_17")
        self.pass_grid.addWidget(self.label_17, 5, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.pass_box)
        self.label_20.setIndent(20)
        self.label_20.setObjectName("label_20")
        self.pass_grid.addWidget(self.label_20, 14, 0, 1, 1)
        self.culmination_alt_lbl = QtWidgets.QLabel(self.pass_box)
        self.culmination_alt_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.culmination_alt_lbl.setObjectName("culmination_alt_lbl")
        self.pass_grid.addWidget(self.culmination_alt_lbl, 10, 1, 1, 1)
        self.meridian_alt_lbl = QtWidgets.QLabel(self.pass_box)
        self.meridian_alt_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meridian_alt_lbl.setObjectName("meridian_alt_lbl")
        self.pass_grid.addWidget(self.meridian_alt_lbl, 5, 1, 1, 1)
        self.culmination_time_lbl = QtWidgets.QLabel(self.pass_box)
        self.culmination_time_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.culmination_time_lbl.setObjectName("culmination_time_lbl")
        self.pass_grid.addWidget(self.culmination_time_lbl, 9, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.goto_rise_btn = QtWidgets.QPushButton(self.pass_box)
        self.goto_rise_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goto_rise_btn.sizePolicy().hasHeightForWidth())
        self.goto_rise_btn.setSizePolicy(sizePolicy)
        self.goto_rise_btn.setObjectName("goto_rise_btn")
        self.horizontalLayout_4.addWidget(self.goto_rise_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.pass_grid.addLayout(self.horizontalLayout_4, 2, 0, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.goto_meridian_btn = QtWidgets.QPushButton(self.pass_box)
        self.goto_meridian_btn.setObjectName("goto_meridian_btn")
        self.horizontalLayout_5.addWidget(self.goto_meridian_btn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.pass_grid.addLayout(self.horizontalLayout_5, 7, 0, 1, 2)
        self.rise_time_lbl = QtWidgets.QLabel(self.pass_box)
        self.rise_time_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rise_time_lbl.setObjectName("rise_time_lbl")
        self.pass_grid.addWidget(self.rise_time_lbl, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.pass_box)
        self.label_18.setIndent(20)
        self.label_18.setObjectName("label_18")
        self.pass_grid.addWidget(self.label_18, 6, 0, 1, 1)
        self.set_time_lbl = QtWidgets.QLabel(self.pass_box)
        self.set_time_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.set_time_lbl.setObjectName("set_time_lbl")
        self.pass_grid.addWidget(self.set_time_lbl, 13, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.pass_box)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pass_grid.addWidget(self.label_4, 13, 0, 1, 1)
        self.culmination_az_lbl = QtWidgets.QLabel(self.pass_box)
        self.culmination_az_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.culmination_az_lbl.setObjectName("culmination_az_lbl")
        self.pass_grid.addWidget(self.culmination_az_lbl, 11, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.pass_grid.addItem(spacerItem7, 12, 0, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.pass_grid.addItem(spacerItem8, 8, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.pass_box)
        self.label_15.setIndent(20)
        self.label_15.setObjectName("label_15")
        self.pass_grid.addWidget(self.label_15, 11, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.pass_grid.addItem(spacerItem9, 3, 0, 1, 2)
        self.verticalLayout_6.addLayout(self.pass_grid)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_7.setSpacing(40)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.prev_pass_btn = QtWidgets.QPushButton(self.pass_box)
        self.prev_pass_btn.setObjectName("prev_pass_btn")
        self.horizontalLayout_7.addWidget(self.prev_pass_btn)
        self.next_pass_btn = QtWidgets.QPushButton(self.pass_box)
        self.next_pass_btn.setObjectName("next_pass_btn")
        self.horizontalLayout_7.addWidget(self.next_pass_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.satellite_layout.addWidget(self.pass_box)
        self.main_layout.addLayout(self.satellite_layout)
        self.status_layout = QtWidgets.QVBoxLayout()
        self.status_layout.setSpacing(6)
        self.status_layout.setObjectName("status_layout")
        self.status_box = QtWidgets.QGroupBox(self.central_widget)
        self.status_box.setObjectName("status_box")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.status_box)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.status_box)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.time_lbl = QtWidgets.QLabel(self.status_box)
        self.time_lbl.setObjectName("time_lbl")
        self.horizontalLayout_3.addWidget(self.time_lbl)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.label_7 = QtWidgets.QLabel(self.status_box)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(20, 0, -1, -1)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.sat_az_lbl = QtWidgets.QLabel(self.status_box)
        self.sat_az_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sat_az_lbl.setObjectName("sat_az_lbl")
        self.gridLayout.addWidget(self.sat_az_lbl, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.status_box)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.sat_alt_lbl = QtWidgets.QLabel(self.status_box)
        self.sat_alt_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sat_alt_lbl.setObjectName("sat_alt_lbl")
        self.gridLayout.addWidget(self.sat_alt_lbl, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.status_box)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.sat_dist_lbl = QtWidgets.QLabel(self.status_box)
        self.sat_dist_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sat_dist_lbl.setObjectName("sat_dist_lbl")
        self.gridLayout.addWidget(self.sat_dist_lbl, 4, 1, 1, 1)
        self.sat_dec_lbl = QtWidgets.QLabel(self.status_box)
        self.sat_dec_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sat_dec_lbl.setObjectName("sat_dec_lbl")
        self.gridLayout.addWidget(self.sat_dec_lbl, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.status_box)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.status_box)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.status_box)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.status_box)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 5, 0, 1, 1)
        self.sat_shadow_lbl = QtWidgets.QLabel(self.status_box)
        self.sat_shadow_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sat_shadow_lbl.setObjectName("sat_shadow_lbl")
        self.gridLayout.addWidget(self.sat_shadow_lbl, 5, 1, 1, 1)
        self.sat_ra_lbl = QtWidgets.QLabel(self.status_box)
        self.sat_ra_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sat_ra_lbl.setObjectName("sat_ra_lbl")
        self.gridLayout.addWidget(self.sat_ra_lbl, 0, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout)
        self.label_12 = QtWidgets.QLabel(self.status_box)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(20, -1, -1, -1)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_23 = QtWidgets.QLabel(self.status_box)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.status_box)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.status_box)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 3, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.status_box)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 2, 0, 1, 1)
        self.tel_ra_lbl = QtWidgets.QLabel(self.status_box)
        self.tel_ra_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tel_ra_lbl.setObjectName("tel_ra_lbl")
        self.gridLayout_2.addWidget(self.tel_ra_lbl, 0, 1, 1, 1)
        self.tel_dec_lbl = QtWidgets.QLabel(self.status_box)
        self.tel_dec_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tel_dec_lbl.setObjectName("tel_dec_lbl")
        self.gridLayout_2.addWidget(self.tel_dec_lbl, 1, 1, 1, 1)
        self.tel_alt_lbl = QtWidgets.QLabel(self.status_box)
        self.tel_alt_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tel_alt_lbl.setObjectName("tel_alt_lbl")
        self.gridLayout_2.addWidget(self.tel_alt_lbl, 2, 1, 1, 1)
        self.tel_az_lbl = QtWidgets.QLabel(self.status_box)
        self.tel_az_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tel_az_lbl.setObjectName("tel_az_lbl")
        self.gridLayout_2.addWidget(self.tel_az_lbl, 3, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_2)
        self.label_26 = QtWidgets.QLabel(self.status_box)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_9.addWidget(self.label_26)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(20, -1, -1, -1)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_27 = QtWidgets.QLabel(self.status_box)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.status_box)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 1, 0, 1, 1)
        self.diff_ra_lbl = QtWidgets.QLabel(self.status_box)
        self.diff_ra_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.diff_ra_lbl.setObjectName("diff_ra_lbl")
        self.gridLayout_3.addWidget(self.diff_ra_lbl, 0, 1, 1, 1)
        self.diff_dec_lbl = QtWidgets.QLabel(self.status_box)
        self.diff_dec_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.diff_dec_lbl.setObjectName("diff_dec_lbl")
        self.gridLayout_3.addWidget(self.diff_dec_lbl, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.label_6 = QtWidgets.QLabel(self.status_box)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(20, -1, -1, -1)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_22 = QtWidgets.QLabel(self.status_box)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 0, 0, 1, 1)
        self.offset_ra_lbl = QtWidgets.QLabel(self.status_box)
        self.offset_ra_lbl.setObjectName("offset_ra_lbl")
        self.gridLayout_6.addWidget(self.offset_ra_lbl, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.status_box)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 1, 0, 1, 1)
        self.offset_dec_lbl = QtWidgets.QLabel(self.status_box)
        self.offset_dec_lbl.setObjectName("offset_dec_lbl")
        self.gridLayout_6.addWidget(self.offset_dec_lbl, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_6)
        self.status_layout.addWidget(self.status_box)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.status_layout.addItem(spacerItem11)
        self.main_layout.addLayout(self.status_layout)
        self.verticalLayout_7.addLayout(self.main_layout)
        self.log_layout = QtWidgets.QGroupBox(self.central_widget)
        self.log_layout.setObjectName("log_layout")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.log_layout)
        self.verticalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.log_browser = QtWidgets.QTextBrowser(self.log_layout)
        self.log_browser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.log_browser.setObjectName("log_browser")
        self.verticalLayout_11.addWidget(self.log_browser)
        self.verticalLayout_7.addWidget(self.log_layout)
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pysattrack"))
        self.indi_box.setTitle(_translate("MainWindow", "INDI"))
        self.host_lbl.setText(_translate("MainWindow", "Host:"))
        self.host_edit.setText(_translate("MainWindow", "localhost"))
        self.port_lbl.setText(_translate("MainWindow", "Port:"))
        self.telescope_lbl.setText(_translate("MainWindow", "Telescope"))
        self.connect_btn.setText(_translate("MainWindow", "Connect"))
        self.indi_lbl.setText(_translate("MainWindow", "Not connected"))
        self.time_box.setTitle(_translate("MainWindow", "Time"))
        self.real_time_btn.setText(_translate("MainWindow", "from computer cloc&k"))
        self.simu_time_btn.setText(_translate("MainWindow", "Simu&lation"))
        self.set_time_btn.setText(_translate("MainWindow", "Set time"))
        self.location_box.setTitle(_translate("MainWindow", "Location"))
        self.latitude_lbl.setText(_translate("MainWindow", "Latitude:"))
        self.longitude_lbl.setText(_translate("MainWindow", "Longitude:"))
        self.altitude_lbl.setText(_translate("MainWindow", "Altitude"))
        self.altitude_spinbox.setSuffix(_translate("MainWindow", " m"))
        self.location_lbl.setText(_translate("MainWindow", "Valid location"))
        self.tracking_box.setTitle(_translate("MainWindow", "Tracking"))
        self.p_gain_lbl.setText(_translate("MainWindow", "P gain:"))
        self.max_speed_DE_lbl.setText(_translate("MainWindow", "Max speed DE:"))
        self.max_speed_DE_spinbox.setSuffix(_translate("MainWindow", " deg/s"))
        self.joystick_speed_lbl.setText(_translate("MainWindow", "Joystick speed:"))
        self.joystick_speed_spinbox.setSuffix(_translate("MainWindow", " deg/s"))
        self.joystick_lbl.setText(_translate("MainWindow", "Joystick:"))
        self.joystick_btn.setText(_translate("MainWindow", "No joystick detected"))
        self.max_speed_RA_lbl.setText(_translate("MainWindow", "Max speed RA"))
        self.max_speed_RA_spinbox.setSuffix(_translate("MainWindow", " deg/s"))
        self.control_box.setTitle(_translate("MainWindow", "Control:"))
        self.down_btn.setText(_translate("MainWindow", "⬇"))
        self.center_btn.setText(_translate("MainWindow", "Track"))
        self.left_btn.setText(_translate("MainWindow", "⬅"))
        self.down_left_btn.setText(_translate("MainWindow", "⬋"))
        self.up_right_btn.setText(_translate("MainWindow", "⬈"))
        self.right_btn.setText(_translate("MainWindow", "➡"))
        self.up_btn.setText(_translate("MainWindow", "⬆"))
        self.up_left_btn.setText(_translate("MainWindow", "⬉"))
        self.down_right_btn.setText(_translate("MainWindow", "⬊"))
        self.slow_btn.setText(_translate("MainWindow", "Slower"))
        self.fast_btn.setText(_translate("MainWindow", "Faster"))
        self.speed_lbl.setText(_translate("MainWindow", "1.2x"))
        self.satellite_box.setTitle(_translate("MainWindow", "Satellite"))
        self.catalog_sat_btn.setText(_translate("MainWindow", "Fro&m catalog"))
        self.catalog_config_btn.setText(_translate("MainWindow", "Config"))
        self.sat_combobox.setItemText(0, _translate("MainWindow", "ISS"))
        self.sat_combobox.setItemText(1, _translate("MainWindow", "Hubble"))
        self.sat_combobox.setItemText(2, _translate("MainWindow", "IRIDIUM 10"))
        self.sat_combobox.setItemText(3, _translate("MainWindow", "IRIDIUM 11"))
        self.sat_combobox.setItemText(4, _translate("MainWindow", "O3B"))
        self.tle_sat_btn.setText(_translate("MainWindow", "From &TLE"))
        self.set_TLE_btn.setText(_translate("MainWindow", "Set TLE"))
        self.sat_lbl.setText(_translate("MainWindow", "Valid elements, 3.1day old"))
        self.pass_box.setTitle(_translate("MainWindow", "Pass"))
        self.label_3.setText(_translate("MainWindow", "Meridian:"))
        self.label_14.setText(_translate("MainWindow", "Alt:"))
        self.meridian_time_lbl.setText(_translate("MainWindow", "2019-02-22 23:00:00"))
        self.label_13.setText(_translate("MainWindow", "Az:"))
        self.set_az_lbl.setText(_translate("MainWindow", "12°12\'13\""))
        self.label.setText(_translate("MainWindow", "Rise:"))
        self.meridian_az_lbl.setText(_translate("MainWindow", "12°12\'13\""))
        self.rise_az_lbl.setText(_translate("MainWindow", "12°12\'13\""))
        self.label_2.setText(_translate("MainWindow", "Culmination:"))
        self.label_17.setText(_translate("MainWindow", "Alt:"))
        self.label_20.setText(_translate("MainWindow", "Az:"))
        self.culmination_alt_lbl.setText(_translate("MainWindow", "12°12\'13\""))
        self.meridian_alt_lbl.setText(_translate("MainWindow", "12°12\'13\""))
        self.culmination_time_lbl.setText(_translate("MainWindow", "2019-02-22 23:00:00"))
        self.goto_rise_btn.setText(_translate("MainWindow", "GOTO"))
        self.goto_meridian_btn.setText(_translate("MainWindow", "GOTO"))
        self.rise_time_lbl.setText(_translate("MainWindow", "2019-02-22 23:00:00"))
        self.label_18.setText(_translate("MainWindow", "Az:"))
        self.set_time_lbl.setText(_translate("MainWindow", "2019-02-22 23:00:00"))
        self.label_4.setText(_translate("MainWindow", "Set:"))
        self.culmination_az_lbl.setText(_translate("MainWindow", "12°12\'13\""))
        self.label_15.setText(_translate("MainWindow", "Az:"))
        self.prev_pass_btn.setText(_translate("MainWindow", "Previous"))
        self.next_pass_btn.setText(_translate("MainWindow", "Next"))
        self.status_box.setTitle(_translate("MainWindow", "Status"))
        self.label_5.setText(_translate("MainWindow", "Time:"))
        self.time_lbl.setText(_translate("MainWindow", "2019-02-22 23:00:00"))
        self.label_7.setText(_translate("MainWindow", "Satellite position:"))
        self.sat_az_lbl.setText(_translate("MainWindow", "12°12\'13\""))
        self.label_10.setText(_translate("MainWindow", "Alt:"))
        self.sat_alt_lbl.setText(_translate("MainWindow", "12°12\'13\""))
        self.label_11.setText(_translate("MainWindow", "Az:"))
        self.sat_dist_lbl.setText(_translate("MainWindow", "9999 km"))
        self.sat_dec_lbl.setText(_translate("MainWindow", "12°12\'13\""))
        self.label_16.setText(_translate("MainWindow", "Distance:"))
        self.label_9.setText(_translate("MainWindow", "DEC:"))
        self.label_8.setText(_translate("MainWindow", "RA:"))
        self.label_19.setText(_translate("MainWindow", "In shadow:"))
        self.sat_shadow_lbl.setText(_translate("MainWindow", "No"))
        self.sat_ra_lbl.setText(_translate("MainWindow", "12h12\'13\""))
        self.label_12.setText(_translate("MainWindow", "Telescope position:"))
        self.label_23.setText(_translate("MainWindow", "DEC:"))
        self.label_21.setText(_translate("MainWindow", "RA:"))
        self.label_25.setText(_translate("MainWindow", "Az:"))
        self.label_24.setText(_translate("MainWindow", "Alt:"))
        self.tel_ra_lbl.setText(_translate("MainWindow", "12h12\'13\""))
        self.tel_dec_lbl.setText(_translate("MainWindow", "12°12\'13\""))
        self.tel_alt_lbl.setText(_translate("MainWindow", "12°12\'13\""))
        self.tel_az_lbl.setText(_translate("MainWindow", "12°12\'13\""))
        self.label_26.setText(_translate("MainWindow", "Difference:"))
        self.label_27.setText(_translate("MainWindow", "RA:"))
        self.label_29.setText(_translate("MainWindow", "DEC:"))
        self.diff_ra_lbl.setText(_translate("MainWindow", "12h12\'13\""))
        self.diff_dec_lbl.setText(_translate("MainWindow", "12°12\'13\""))
        self.label_6.setText(_translate("MainWindow", "Offset:"))
        self.label_22.setText(_translate("MainWindow", "RA:"))
        self.offset_ra_lbl.setText(_translate("MainWindow", "TextLabel"))
        self.label_32.setText(_translate("MainWindow", "DEC:"))
        self.offset_dec_lbl.setText(_translate("MainWindow", "TextLabel"))
        self.log_layout.setTitle(_translate("MainWindow", "Log"))


