# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/test/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 1001)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.hostLabel = QtWidgets.QLabel(self.groupBox)
        self.hostLabel.setObjectName("hostLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.hostLabel)
        self.hostLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.hostLineEdit.setObjectName("hostLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hostLineEdit)
        self.portLabel = QtWidgets.QLabel(self.groupBox)
        self.portLabel.setObjectName("portLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.portLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.portLineEdit.setObjectName("portLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.portLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setEditable(True)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.latitudeLabel = QtWidgets.QLabel(self.groupBox_3)
        self.latitudeLabel.setObjectName("latitudeLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.latitudeLabel)
        self.latitudeLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.latitudeLineEdit.setObjectName("latitudeLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.latitudeLineEdit)
        self.longitudeLabel = QtWidgets.QLabel(self.groupBox_3)
        self.longitudeLabel.setObjectName("longitudeLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.longitudeLabel)
        self.longitudeLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.longitudeLineEdit.setObjectName("longitudeLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.longitudeLineEdit)
        self.altitudeLabel = QtWidgets.QLabel(self.groupBox_3)
        self.altitudeLabel.setObjectName("altitudeLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.altitudeLabel)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setMaximum(999999)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.timeOffsetLabel = QtWidgets.QLabel(self.groupBox_3)
        self.timeOffsetLabel.setObjectName("timeOffsetLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.timeOffsetLabel)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_2.setMinimum(-6000)
        self.spinBox_2.setMaximum(6000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.methodLabel = QtWidgets.QLabel(self.groupBox_4)
        self.methodLabel.setObjectName("methodLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.methodLabel)
        self.methodComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.methodComboBox.setObjectName("methodComboBox")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.methodComboBox)
        self.pGainLabel = QtWidgets.QLabel(self.groupBox_4)
        self.pGainLabel.setObjectName("pGainLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pGainLabel)
        self.pGainDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.pGainDoubleSpinBox.setObjectName("pGainDoubleSpinBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pGainDoubleSpinBox)
        self.tauILabel = QtWidgets.QLabel(self.groupBox_4)
        self.tauILabel.setObjectName("tauILabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tauILabel)
        self.tauIDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.tauIDoubleSpinBox.setObjectName("tauIDoubleSpinBox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tauIDoubleSpinBox)
        self.tauDLabel = QtWidgets.QLabel(self.groupBox_4)
        self.tauDLabel.setObjectName("tauDLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.tauDLabel)
        self.tauDDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.tauDDoubleSpinBox.setObjectName("tauDDoubleSpinBox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tauDDoubleSpinBox)
        self.maxRateLabel = QtWidgets.QLabel(self.groupBox_4)
        self.maxRateLabel.setObjectName("maxRateLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.maxRateLabel)
        self.saturationLabel = QtWidgets.QLabel(self.groupBox_4)
        self.saturationLabel.setObjectName("saturationLabel")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.saturationLabel)
        self.saturationDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.saturationDoubleSpinBox.setObjectName("saturationDoubleSpinBox")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.saturationDoubleSpinBox)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_5.addWidget(self.pushButton_3)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "INDI"))
        self.hostLabel.setText(_translate("MainWindow", "Host:"))
        self.portLabel.setText(_translate("MainWindow", "Port:"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Satellite"))
        self.radioButton.setText(_translate("MainWindow", "Fro&m catalog"))
        self.pushButton_2.setText(_translate("MainWindow", "Config"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ISS"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Hubble"))
        self.comboBox.setItemText(2, _translate("MainWindow", "IRIDIUM 10"))
        self.comboBox.setItemText(3, _translate("MainWindow", "IRIDIUM 11"))
        self.comboBox.setItemText(4, _translate("MainWindow", "O3B"))
        self.radioButton_2.setText(_translate("MainWindow", "From &TLE"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "1 25544U 98067A   19051.72727322  .00000700  00000-0  18331-4 0  9995\n"
"2 25544  51.6404 220.3127 0005805  48.6002  26.2072 15.53278986157160"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Observer"))
        self.latitudeLabel.setText(_translate("MainWindow", "Latitude:"))
        self.longitudeLabel.setText(_translate("MainWindow", "Longitude:"))
        self.altitudeLabel.setText(_translate("MainWindow", "Altitude"))
        self.spinBox.setSuffix(_translate("MainWindow", " m"))
        self.timeOffsetLabel.setText(_translate("MainWindow", "Time offset:"))
        self.spinBox_2.setSuffix(_translate("MainWindow", " min"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Tracking"))
        self.methodLabel.setText(_translate("MainWindow", "Method:"))
        self.methodComboBox.setItemText(0, _translate("MainWindow", "Goto"))
        self.methodComboBox.setItemText(1, _translate("MainWindow", "Move"))
        self.methodComboBox.setItemText(2, _translate("MainWindow", "Timed moves"))
        self.methodComboBox.setItemText(3, _translate("MainWindow", "Speed"))
        self.pGainLabel.setText(_translate("MainWindow", "P gain:"))
        self.tauILabel.setText(_translate("MainWindow", "Tau I"))
        self.tauDLabel.setText(_translate("MainWindow", "Tau D"))
        self.maxRateLabel.setText(_translate("MainWindow", "Max rate:"))
        self.saturationLabel.setText(_translate("MainWindow", "Saturation:"))
        self.pushButton_3.setText(_translate("MainWindow", "Track"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

